### ISSUE TITLE
 Problems When I Training

### ISSUE THREAD

**Issue by guoyan1991** [heromanba/3D-R2N2-PyTorch#1]
I had the following problems during training, I guess there are some problem in the loop in the forward function in base_gru_net. I'm looking forward to your help!

Traceback (most recent call last):
  File "main.py", line 121, in <module>
    main()
  File "main.py", line 111, in main
    train_net()
  File "/home/may/下载/3D-R2N2-PyTorch-master/lib/train_net.py", line 22, in func_wrapper
    return func(*args, **kwargs)
  File "/home/may/下载/3D-R2N2-PyTorch-master/lib/train_net.py", line 75, in train_net
    solver.train(train_queue, val_queue)
  File "/home/may/下载/3D-R2N2-PyTorch-master/lib/solver.py", line 113, in train
    loss = self.train_loss(batch_img, batch_voxel)
  File "/home/may/下载/3D-R2N2-PyTorch-master/lib/solver.py", line 67, in train_loss
    loss = self.net(x, y, test=False)
  File "/home/may/anaconda2/envs/py3torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/may/下载/3D-R2N2-PyTorch-master/models/base_gru_net.py", line 76, in forward
    gru_out, update_gate = self.encoder(x[time], h, u, time)
  File "/home/may/anaconda2/envs/py3torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 4 positional arguments but 5 were given
[INFO/MainProcess] process shutting down
[INFO/MainProcess] calling join() for process ReconstructionDataProcess-6

**Comment by heromanba** [comment]
Sorry to reply late, you may try the new version
