### ISSUE TITLE
Problem when i ran demo.py

### ISSUE THREAD

**Issue by zhanqan** [heromanba/3D-R2N2-PyTorch#2]
Traceback (most recent call last):
  File "demo.py", line 90, in <module>
    main()
  File "demo.py", line 67, in main
    net.load(DEFAULT_WEIGHTS)                        # load downloaded weights
  File "/home/zhangq/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResidualGRUNet' object has no attribute 'load'

**Comment by heromanba** [comment]
Sorry to reply late, you may try the new version.
